import { AiOutlineReload } from 'react-icons/ai'
import { BiGroup, BiHeadphone, BiInfoCircle, BiMessageRounded, BiNews, BiPalette, BiUserCircle } from 'react-icons/bi'
import { BsFileMedical } from 'react-icons/bs'
import { FiBell, FiClipboard, FiClock, FiFileText, FiHome, FiMenu, FiSettings, FiUser } from 'react-icons/fi'
import {
    HiOutlineAcademicCap,
    HiOutlineCalendar,
    HiOutlineClipboardCheck,
    HiOutlineFlag,
    HiOutlineViewGrid,
} from 'react-icons/hi'

import { isProduction } from '@shared/consts'

import { IRoutes } from '../consts'
import {
    ALERTS_ROUTE,
    ALL_ROUTE,
    ALL_STUDENTS_ROUTE,
    CHAT_ROUTE,
    DOCLIST_ROUTE,
    ELECTRONIC_INTERACTION_TYPE,
    FEEDBACK_ROUTE,
    FILTERED_ALL_STUDENTS_ROUTE,
    FILTERED_ALL_TEACHERS_ROUTE,
    HOME_ROUTE,
    INSTRUCTIONS_ROUTE,
    LK_NOTIFICATIONS_ROUTE,
    PERSONAL_ELECTRONIC_INTERACTION,
    PROFILE_ROUTE,
    SAFETY_INFORMATION,
    SCHEDULE_CURRENT_ROUTE,
    SCHEDULE_FILTER_ROUTE,
    SCHEDULE_RETAKE_ROUTE,
    SCHEDULE_ROUTE,
    SCHEDULE_SEMESTR_ROUTE,
    SCHEDULE_SESSION_ROUTE,
    SETTINGS_APPEARANCE_ROUTE,
    SETTINGS_CUSTOMIZE_MENU_PAGE_ROUTE,
    SETTINGS_HOME_PAGE_ROUTE,
    SETTINGS_NOTIFICATIONS,
    SETTINGS_PERSONAl_ROUTE,
    SETTINGS_ROUTE,
    SETTINGS_TUTORIAL,
    TECHNICAL_MAINTENANCE,
    TEMPLATE_CHAT_ROUTE,
    TEMPLATE_USEFUL_INFO_ROUTE,
    VACCINATION,
} from '../paths'

export const generalRoutes: Omit<IRoutes, 'Component'> = {
    all: {
        id: 'all',
        title: 'Все разделы',
        icon: HiOutlineViewGrid,
        path: ALL_ROUTE,
        color: 'lightGreen',
        isTemplate: false,
        show: false,
        group: 'GENERAL',
        withoutBackButton: true,
        pageSize: 'big',
    },
    doclist: {
        id: 'doclist',
        title: 'Ознакомление с документами',
        icon: FiFileText,
        path: DOCLIST_ROUTE,
        color: 'blue',
        isTemplate: false,
        group: 'FINANCES_DOCS',
    },
    alerts: {
        id: 'alerts',
        title: 'Новости',
        icon: BiNews,
        path: ALERTS_ROUTE,
        color: 'purple',
        isTemplate: false,
        group: 'COMMUNICATION',
        keywords: ['Оповещения'],
    },
    home: {
        id: 'home',
        title: 'Главная',
        icon: FiHome,
        path: HOME_ROUTE,
        color: 'blue',
        isTemplate: false,
        group: 'GENERAL',
        keywords: ['домой'],
        withoutHeader: true,
    },
    settings: {
        id: 'settings',
        title: 'Настройки',
        icon: FiSettings,
        path: SETTINGS_ROUTE,
        color: 'lightGreen',
        isTemplate: true,
        show: true,
        group: 'GENERAL',
    },
    profile: {
        id: 'profile',
        title: 'Профиль',
        icon: BiUserCircle,
        path: PROFILE_ROUTE,
        color: 'purple',
        isTemplate: false,
        group: 'GENERAL',
        withoutHeader: true,
    },
    'lk-notifications': {
        id: 'lk-notifications',
        title: 'Уведомления',
        icon: FiBell,
        path: LK_NOTIFICATIONS_ROUTE,
        color: 'orange',
        isTemplate: false,
        group: 'GENERAL',
        keywords: ['Оповещения'],
    },
    'electronic-interaction-agreement': {
        id: 'electronic-interaction-agreement',
        title: 'Соглашение об электронном взаимодействии',
        shortTitle: 'Соглашение об электр...',
        icon: HiOutlineClipboardCheck,
        path: ELECTRONIC_INTERACTION_TYPE,
        color: 'blue',
        isTemplate: false,
        group: 'GENERAL',
        pageSize: 'small',
        menuPath: PERSONAL_ELECTRONIC_INTERACTION,
    },
    chat: {
        id: 'chat',
        title: 'Сообщения',
        icon: BiMessageRounded,
        path: CHAT_ROUTE,
        color: 'red',
        group: 'COMMUNICATION',
        keywords: ['чат', 'сообщения', 'написать'],
        pageSize: 'big',
        isTemplate: false,
        planeHeader: false,
        hiddenTitle: true,
    },
    'specific-chat': {
        id: 'specific-chat',
        title: 'Сообщения',
        icon: BiMessageRounded,
        path: TEMPLATE_CHAT_ROUTE,
        color: 'red',
        pageSize: 'big',
        isTemplate: false,
        planeHeader: false,
        hiddenTitle: true,
        group: 'COMMUNICATION',
        isSubPage: true,
        show: false,
    },
    schedule: {
        id: 'schedule',
        title: 'Расписание',
        icon: FiClock,
        path: SCHEDULE_ROUTE,
        menuPath: SCHEDULE_CURRENT_ROUTE,
        color: 'pink',
        isTemplate: true,
        show: true,
        group: 'LEARNING_ACTIVITIES',
        pageSize: 'large',
    },
    'all-students': {
        id: 'all-students',
        title: 'Студенты',
        icon: BiGroup,
        path: ALL_STUDENTS_ROUTE,
        color: 'lightBlue',
        isTemplate: false,
        group: 'COMMUNICATION',
        keywords: ['одногруппники', 'ученики'],
    },
    feedback: {
        id: 'feedback',
        title: 'Обратная связь',
        icon: BiHeadphone,
        path: FEEDBACK_ROUTE,
        color: 'blue',
        isTemplate: false,
        group: 'COMMUNICATION',
    },
    instructions: {
        id: 'instructions',
        title: 'Полезная информация',
        icon: FiClipboard,
        path: INSTRUCTIONS_ROUTE,
        color: 'blue',
        isTemplate: false,
        group: 'GENERAL',
        show: false,
    },
    vaccination: {
        id: 'vaccination',
        title: 'Вакцинация',
        icon: BsFileMedical,
        path: VACCINATION,
        color: 'blue',
        isTemplate: false,
        group: 'GENERAL',
        keywords: ['медицинская', 'справка', 'грипп', 'dfrwbyfwbz'],
        isOldLK: true,
        show: !isProduction,
    },
    'safety-information': {
        id: 'safety-information',
        title: 'Безопасность',
        icon: BiInfoCircle,
        path: SAFETY_INFORMATION,
        color: 'red',
        isTemplate: true,
        group: 'GENERAL',
    },
    'technical-maintenance': {
        id: 'technical-maintenance',
        hiddenTitle: true,
        title: 'КСУТО',
        icon: FiFileText,
        color: 'blue',
        path: TECHNICAL_MAINTENANCE,
        isTemplate: false,
        group: 'GENERAL',
        isSubPage: true,
    },
}

export const scheduleRoutes: IRoutes = {
    'schedule-current': {
        id: 'schedule-current',
        title: 'Текущее расписание',
        shortTitle: 'Текущее',
        icon: FiClock,
        path: SCHEDULE_CURRENT_ROUTE,
        color: 'pink',
        isTemplate: false,
        show: false,
        group: 'OTHER',
        pageSize: 'large',
    },
    'schedule-semestr': {
        id: 'schedule-semestr',
        title: 'Расписание на семестр',
        shortTitle: 'Семестр',
        icon: HiOutlineCalendar,
        path: SCHEDULE_SEMESTR_ROUTE,
        color: 'orange',
        isTemplate: false,
        show: true,
        group: 'OTHER',
        pageSize: 'large',
    },
    'schedule-session': {
        id: 'schedule-session',
        title: 'Расписание сессии',
        shortTitle: 'Сессия',
        icon: HiOutlineFlag,
        path: SCHEDULE_SESSION_ROUTE,
        color: 'red',
        isTemplate: false,
        show: true,
        group: 'OTHER',
        pageSize: 'large',
    },
    'schedule-retake': {
        id: 'schedule-retake',
        title: 'Пересдачи',
        icon: AiOutlineReload,
        path: SCHEDULE_RETAKE_ROUTE,
        color: 'red',
        isTemplate: false,
        show: true,
        group: 'OTHER',
        pageSize: 'large',
    },
}

export const settingsRoutes: IRoutes = {
    'settings-appearance': {
        id: 'settings-appearance',
        title: 'Настройки. Внешний вид',
        icon: BiPalette,
        path: SETTINGS_APPEARANCE_ROUTE,
        color: 'purple',
        isTemplate: true,
        show: true,
        group: 'OTHER',
        isSubPage: true,
        subPageHeaderTitle: 'Внешний вид',
        fallbackPrevPage: SETTINGS_ROUTE,
        backButtonText: 'Настройки',
    },
    'settings-personal': {
        id: 'settings-personal',
        title: 'Настройки. Аккаунт',
        icon: FiUser,
        path: SETTINGS_PERSONAl_ROUTE,
        color: 'pink',
        isTemplate: true,
        show: true,
        group: 'OTHER',
        isSubPage: true,
        subPageHeaderTitle: 'Аккаунт',
        fallbackPrevPage: SETTINGS_ROUTE,
        backButtonText: 'Настройки',
    },
    'settings-home-page': {
        id: 'settings-home-page',
        title: 'Настройки. Главная страница',
        icon: FiHome,
        path: SETTINGS_HOME_PAGE_ROUTE,
        color: 'blue',
        isTemplate: true,
        show: true,
        group: 'OTHER',
        isSubPage: true,
        subPageHeaderTitle: 'Главная страница',
        fallbackPrevPage: SETTINGS_ROUTE,

        backButtonText: 'Настройки',
    },
    'settings-customize-menu': {
        id: 'settings-customize-menu',
        title: 'Настройки. Меню',
        icon: FiMenu,
        path: SETTINGS_CUSTOMIZE_MENU_PAGE_ROUTE,
        color: 'red',
        isTemplate: true,
        show: true,
        isSubPage: true,
        subPageHeaderTitle: 'Меню',
        fallbackPrevPage: SETTINGS_ROUTE,

        backButtonText: 'Настройки',
    },
    'settings-notifications': {
        id: 'settings-notifications',
        title: 'Настройки. Уведомления',
        icon: FiBell,
        path: SETTINGS_NOTIFICATIONS,
        color: 'orange',
        isTemplate: true,
        show: true,
        isSubPage: true,
        subPageHeaderTitle: 'Уведомления',
        fallbackPrevPage: SETTINGS_ROUTE,

        backButtonText: 'Настройки',
    },
    'settings-tutorial': {
        id: 'settings-tutorial',
        title: 'Настройки. Обучение',
        icon: HiOutlineAcademicCap,
        path: SETTINGS_TUTORIAL,
        color: 'green',
        isTemplate: true,
        show: true,
        isSubPage: true,
        subPageHeaderTitle: 'Обучение',
        fallbackPrevPage: SETTINGS_ROUTE,

        backButtonText: 'Настройки',
    },
}

export const generalHiddenRoutes: IRoutes = {
    // 'teachers-schedule': {
    //     id: 'teachers-schedule',
    //     title: 'Расписание преподавателя',
    //     icon: <BiIdCard />,
    //     path: FILTER_SCHEDULE,
    //     Component: TeachersSchedule,
    //     color: 'blue',
    //     isTemplate: false,
    //     show: false,
    //     group: 'OTHER',
    //     pageSize: 'large',
    // },
    'schedule-filter': {
        id: 'schedule-filter',
        title: 'Расписание',
        icon: FiClock,
        path: SCHEDULE_FILTER_ROUTE,
        color: 'pink',
        isTemplate: false,
        show: false,
        group: 'OTHER',
        pageSize: 'large',
    },
    ...scheduleRoutes,
    'filtered-all-students': {
        id: 'filtered-all-students',
        title: 'Все студенты',
        icon: BiGroup,
        path: FILTERED_ALL_STUDENTS_ROUTE,
        color: 'blue',
        isTemplate: false,
        show: false,
        group: 'OTHER',
    },
    // move to student's after #ASM
    'filtered-all-teachers': {
        id: 'filtered-all-teachers',
        title: 'Все сотрудники',
        icon: BiGroup,
        path: FILTERED_ALL_TEACHERS_ROUTE,
        color: 'blue',
        isTemplate: false,
        show: false,
        group: 'OTHER',
    },
    'useful-info-template': {
        id: `useful-info-template`,
        title: `Полезная информация`,
        path: TEMPLATE_USEFUL_INFO_ROUTE,
        color: 'grey',
        isTemplate: true,
        show: false,
    },
}
