import {
    ProjectActivityManagerProject,
    StudentActivitiesColumn,
    StudentActivityData,
    StudentActivityResult,
} from '@features/table-project-activities-manager'

export const MOCK_PROJ_ACTIVITES_MANAGER_PROJECTS: ProjectActivityManagerProject[] = [
    {
        id: 1,
        name: 'Дальнейшее развитие различных форм деятельности',
    },
    {
        id: 2,
        name: 'Участие в формировании форм развития',
    },
    {
        id: 3,
        name: 'Эксперимент проверки соответствующих условий активизации',
    },
    {
        id: 4,
        name: 'Укрепление и развитие структуры',
    },
    {
        id: 5,
        name: 'Эксперимент проверки модели развития',
    },
    {
        id: 6,
        name: 'Уточнение новых предложений',
    },
    {
        id: 7,
        name: 'Разработка существенных финансовых и административных условий',
    },
]

export const MOCK_PROJ_ACTIVITIES_MANAGER_CURRENT_SEMESTER: StudentActivityData[] = [
    {
        studentId: 1,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Развитие различных форм деятельности',
        [StudentActivitiesColumn.manager]: 'Арзамазов Иван Владимирович',
        [StudentActivitiesColumn.group]: '123-456',
        [StudentActivitiesColumn.name]: 'Трофимов Владимир Фёдорович',
        [StudentActivitiesColumn.email]: 'vuweummureuffei-8167@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 15,
        [StudentActivitiesColumn.secondValidation]: 20,
        [StudentActivitiesColumn.defensePoints]: 30,
        [StudentActivitiesColumn.resultPoints]: 65,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 2,
    },
    {
        studentId: 2,
        expelled: true,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Процесс внедрения и модернизации позиций',
        [StudentActivitiesColumn.manager]: 'Тамразова Илона Геннадьевна',
        [StudentActivitiesColumn.group]: '234-567',
        [StudentActivitiesColumn.name]: 'Романов Богдан Михайлович',
        [StudentActivitiesColumn.email]: 'zittessujaffa-8979@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 10,
        [StudentActivitiesColumn.secondValidation]: 15,
        [StudentActivitiesColumn.defensePoints]: 20,
        [StudentActivitiesColumn.resultPoints]: 45,
        [StudentActivitiesColumn.result]: StudentActivityResult.notPassed,
        [StudentActivitiesColumn.stars]: 1,
    },
    {
        studentId: 3,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Процесс внедрения и модернизации направлений прогрессивного развития',
        [StudentActivitiesColumn.manager]: 'Рабичева Татьяна Сергеевна',
        [StudentActivitiesColumn.group]: '234-567',
        [StudentActivitiesColumn.name]: 'Макаров Всеволод Данилович',
        [StudentActivitiesColumn.email]: 'sirobreuddagrou-9354@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 15,
        [StudentActivitiesColumn.secondValidation]: 20,
        [StudentActivitiesColumn.defensePoints]: 30,
        [StudentActivitiesColumn.resultPoints]: 70,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 0,
    },
    {
        studentId: 4,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Консультация с широким активом',
        [StudentActivitiesColumn.manager]: 'Новикова Екатерина Борисовна',
        [StudentActivitiesColumn.group]: '234-567',
        [StudentActivitiesColumn.name]: 'Петровский Алексей Антонович',
        [StudentActivitiesColumn.email]: 'suffutteisippe-9314@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 15,
        [StudentActivitiesColumn.secondValidation]: 10,
        [StudentActivitiesColumn.defensePoints]: 30,
        [StudentActivitiesColumn.resultPoints]: 60,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 2,
    },
    {
        studentId: 5,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Анализ системы обучения кадров',
        [StudentActivitiesColumn.manager]: 'Ларцева Татьяна Александровна',
        [StudentActivitiesColumn.group]: '321-433',
        [StudentActivitiesColumn.name]: 'Алексеев Артём Глебович',
        [StudentActivitiesColumn.email]: 'broifaubrautrele-3241@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 25,
        [StudentActivitiesColumn.secondValidation]: 10,
        [StudentActivitiesColumn.defensePoints]: 30,
        [StudentActivitiesColumn.resultPoints]: 65,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 2,
    },
    {
        studentId: 6,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Анализ системы обучения кадров',
        [StudentActivitiesColumn.manager]: 'Ларцева Татьяна Александровна',
        [StudentActivitiesColumn.group]: '322-435',
        [StudentActivitiesColumn.name]: 'Титов Иван Тимурович',
        [StudentActivitiesColumn.email]: 'trettaugaxopro-9278@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 25,
        [StudentActivitiesColumn.secondValidation]: 15,
        [StudentActivitiesColumn.defensePoints]: 50,
        [StudentActivitiesColumn.resultPoints]: 80,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 1,
    },
    {
        studentId: 7,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Идейные соображения высшего порядка',
        [StudentActivitiesColumn.manager]: 'Щербакова Галина Владимировна',
        [StudentActivitiesColumn.group]: '531-332',
        [StudentActivitiesColumn.name]: 'Крылова Виктория Артёмовна',
        [StudentActivitiesColumn.email]: 'kaubuprallove-3626@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 15,
        [StudentActivitiesColumn.secondValidation]: 15,
        [StudentActivitiesColumn.defensePoints]: 10,
        [StudentActivitiesColumn.resultPoints]: 40,
        [StudentActivitiesColumn.result]: StudentActivityResult.notPassed,
        [StudentActivitiesColumn.stars]: 0,
    },
    {
        studentId: 8,
        expelled: false,
        isPrevSemester: false,
        [StudentActivitiesColumn.subproject]: 'Идейные соображения высшего порядка',
        [StudentActivitiesColumn.manager]: 'Файзуллин Дмитрий Эдуардович',
        [StudentActivitiesColumn.group]: '114-385',
        [StudentActivitiesColumn.name]: 'Алексеева Алиса Константиновна',
        [StudentActivitiesColumn.email]: 'meffeuvoippikoi-2221@yopmail.com',
        [StudentActivitiesColumn.firstValidation]: 15,
        [StudentActivitiesColumn.secondValidation]: 15,
        [StudentActivitiesColumn.defensePoints]: 40,
        [StudentActivitiesColumn.resultPoints]: 70,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 1,
    },
]

export const MOCK_PROJ_ACTIVITIES_MANAGER_PREV_SEMESTER: StudentActivityData[] = [
    {
        studentId: 1,
        expelled: false,
        isPrevSemester: true,
        [StudentActivitiesColumn.subproject]: 'Формирование дальнейших направлений развития',
        [StudentActivitiesColumn.manager]: 'Новикова Екатерина Борисовна',
        [StudentActivitiesColumn.group]: '432-221',
        [StudentActivitiesColumn.name]: 'Беляков Владимир Иванович',
        [StudentActivitiesColumn.email]: 'xapauseittotrau-4323@yopmail.com',
        [StudentActivitiesColumn.transferredPoints]: 30,
        [StudentActivitiesColumn.retaking]: 30,
        [StudentActivitiesColumn.resultPoints]: 60,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 0,
    },
    {
        studentId: 2,
        expelled: false,
        isPrevSemester: true,
        [StudentActivitiesColumn.subproject]: 'Постоянный количественный рост',
        [StudentActivitiesColumn.manager]: 'Файзуллин Дмитрий Эдуардович',
        [StudentActivitiesColumn.group]: '432-743',
        [StudentActivitiesColumn.name]: 'Зотов Александр Георгиевич',
        [StudentActivitiesColumn.email]: 'meimouwuloce-1856@yopmail.com',
        [StudentActivitiesColumn.transferredPoints]: 30,
        [StudentActivitiesColumn.retaking]: 40,
        [StudentActivitiesColumn.resultPoints]: 70,
        [StudentActivitiesColumn.result]: StudentActivityResult.passed,
        [StudentActivitiesColumn.stars]: 2,
    },
    {
        studentId: 3,
        expelled: false,
        isPrevSemester: true,
        [StudentActivitiesColumn.subproject]: 'Создание систем массового участия',
        [StudentActivitiesColumn.manager]: 'Рабичева Татьяна Сергеевна',
        [StudentActivitiesColumn.group]: '582-536',
        [StudentActivitiesColumn.name]: 'Белоусова Алиса Ивановна',
        [StudentActivitiesColumn.email]: 'keppoletreiyou-6449@yopmail.com',
        [StudentActivitiesColumn.transferredPoints]: 10,
        [StudentActivitiesColumn.retaking]: 20,
        [StudentActivitiesColumn.resultPoints]: 30,
        [StudentActivitiesColumn.result]: StudentActivityResult.notPassed,
        [StudentActivitiesColumn.stars]: 0,
    },
    {
        studentId: 4,
        expelled: false,
        isPrevSemester: true,
        [StudentActivitiesColumn.subproject]: 'Создание систем массового участия',
        [StudentActivitiesColumn.manager]: 'Рабичева Татьяна Сергеевна',
        [StudentActivitiesColumn.group]: '537-754',
        [StudentActivitiesColumn.name]: 'Кузнецов Александр Максимович',
        [StudentActivitiesColumn.email]: 'craucrounotteulli-1612@yopmail.com',
        [StudentActivitiesColumn.transferredPoints]: 30,
        [StudentActivitiesColumn.retaking]: 20,
        [StudentActivitiesColumn.resultPoints]: 50,
        [StudentActivitiesColumn.result]: StudentActivityResult.notPassed,
        [StudentActivitiesColumn.stars]: 1,
    },
]
