import { APPLICATIONS_ROUTE } from './private'

export const DORMITORY = '/dormitory'
export const JOB_ROUTE = '/job'
export const APPLICATION_FOR_SUPERIOR_ROOM_ROUTE = '/application-for-superior-room'
export const ACAD_PERFORMANCE_ROUTE = '/acad-performance'

//hidden routes
export const CLARIFICATION_OF_PASSPORT_DATA_ROUTE = APPLICATIONS_ROUTE + '/clarification-of-passport-data'
export const ARBITRARY_REQUEST_ROUTE = APPLICATIONS_ROUTE + '/arbitrary-request'
export const STUDENT_EMPLOYMENT_ROUTE = APPLICATIONS_ROUTE + '/student-employment'
export const SOCIAL_SCOLLARSHIP = APPLICATIONS_ROUTE + '/social-scollarship'
export const CERTIFICATE_OF_ATTENDANCE = APPLICATIONS_ROUTE + '/certificate-of-attendance'
export const SOCIAL_AGENCIES = APPLICATIONS_ROUTE + '/social-agencies'
export const PAPER_CALL = APPLICATIONS_ROUTE + '/paper-call'
export const REGULAR_ACCOMMODATION = APPLICATIONS_ROUTE + '/regular-accommodation'
export const FULL_TIME_PART_TIME_FORM = APPLICATIONS_ROUTE + '/full-time-part-time-form'
export const ACCOMMODATION_CORRESPONDENCE_FORM = APPLICATIONS_ROUTE + '/accommodation-correspondence-form'
export const ACADEMIC_LEAVE_ACCOMMODATION = APPLICATIONS_ROUTE + '/academic-leave-accommodation'
export const PREFERENTIAL_ACCOMMODATION = APPLICATIONS_ROUTE + '/preferential-accommodation'
export const FAMILY_ROOM = APPLICATIONS_ROUTE + '/family-room'
export const TERMINATION_OF_EMPLOYMENT_CONTRACT = APPLICATIONS_ROUTE + '/termination-of-employment-contract'
export const RELOCATION_INSIDE_HOSTEL = APPLICATIONS_ROUTE + '/relocation-inside-hostel'
export const RELOCATION_TO_ANOTHER_HOSTEL = APPLICATIONS_ROUTE + '/relocation-to-another-hostel'
export const ACCOMMODATION_FOR_GRADUATES = APPLICATIONS_ROUTE + '/accommodation-for-graduates'
export const PAYMENT_RECIPIENT = APPLICATIONS_ROUTE + '/payment-recipient'
export const RESTORING_THE_MAGNETIC_PASS = APPLICATIONS_ROUTE + '/restoring-the-magnetic-pass'
export const RETAKE_FOR_DIPLOMA = APPLICATIONS_ROUTE + '/retake-for-diploma'
export const MILITARY_REGISTRATION_DOCUMENTS = APPLICATIONS_ROUTE + '/military-registration-documents'
export const MILITARY_REGISTRATION = APPLICATIONS_ROUTE + '/military-registration'
export const MILITARY_FORM_4 = APPLICATIONS_ROUTE + '/military-form-4'
export const MILITARY_FORM_5 = APPLICATIONS_ROUTE + '/military-form-5'
export const MILITARY_COPIES = APPLICATIONS_ROUTE + '/military-copies'
export const FINANCIAL_SUPPORT = APPLICATIONS_ROUTE + '/financial-support'
export const FINANCIAL_ASSISTANCE = APPLICATIONS_ROUTE + '/financial-assistance'
export const INCREASED_STATE_ACADEMIC_SCHOLARSHIP = APPLICATIONS_ROUTE + '/increased-state-academic-scholarship'
export const CHANGING_PERSONAL_DATA = APPLICATIONS_ROUTE + '/changing-personal-data'
export const STUDENT_STATUS = APPLICATIONS_ROUTE + '/student-status'
export const FAMILY_CONTACTS = APPLICATIONS_ROUTE + '/family-contacts'
export const MEDICAL_CERTIFICATES_086 = APPLICATIONS_ROUTE + '/medical-certificates-086'
export const STATE_ACCREDITATION = APPLICATIONS_ROUTE + '/state-accreditation'
export const MILITARY_REGISTRATION_CARD = APPLICATIONS_ROUTE + '/military-registration-card'
export const HOLIDAYS_AFTER_TRAINING = APPLICATIONS_ROUTE + '/holidays-after-training'
export const PROVISION_ACADEMIC_LEAVE = APPLICATIONS_ROUTE + '/provision-academic-leave'
export const EXIT_ACADEMIC_LEAVE = APPLICATIONS_ROUTE + '/exit-academic-leave'
export const INDEPENDENTLY_DEDUCTED = APPLICATIONS_ROUTE + '/independently-deducted'
export const EXTENSION_ATTESTATION = APPLICATIONS_ROUTE + '/extension-attestation'
export const PHYSICAL_EDUCATION_STUDENT = '/physical-education/student'
