import reactLazyWithRetry from '@fatso83/retry-dynamic-import/react-lazy'

export const AllPages = reactLazyWithRetry(() => import('@pages/all-pages'))
export const AllStudentsPage = reactLazyWithRetry(() => import('@pages/all-students'))
export const AllTeachersPage = reactLazyWithRetry(() => import('@pages/all-teachers'))
export const CantAccessPage = reactLazyWithRetry(() => import('@pages/cant-access'))
export const ChatPage = reactLazyWithRetry(() => import('@pages/chat'))
export const ElectronicInteractionAgreementPage = reactLazyWithRetry(
    () => import('@pages/electronic-interaction-agreement'),
)
export const FeedbackPage = reactLazyWithRetry(() => import('@pages/feedback'))
export const ForgotPasswordPage = reactLazyWithRetry(() => import('@pages/forgot-password'))
export const AlertsPage = reactLazyWithRetry(() => import('@pages/alerts'))
export const Home = reactLazyWithRetry(() => import('@pages/home'))
export const InstructionsPage = reactLazyWithRetry(() => import('@pages/instructions'))
export const PaymentsPage = reactLazyWithRetry(() => import('@pages/payments'))
export const ProfilePage = reactLazyWithRetry(() => import('@pages/profile'))
export const SchedulePage = reactLazyWithRetry(() => import('@pages/schedule'))
export const ScheduleCurrent = reactLazyWithRetry(() => import('@pages/schedule/ui/current-schedule'))
export const ScheduleSemestr = reactLazyWithRetry(() => import('@pages/schedule/ui/semestr-schedule'))
export const ScheduleSession = reactLazyWithRetry(() => import('@pages/schedule/ui/session-schedule'))
export const ScheduleRetake = reactLazyWithRetry(() => import('@pages/schedule/ui/retake-schedule'))
export const SettingsPage = reactLazyWithRetry(() => import('@pages/settings'))
export const Account = reactLazyWithRetry(() => import('@pages/settings/pages/account'))
export const Appearance = reactLazyWithRetry(() => import('@pages/settings/pages/appearance'))
export const Security = reactLazyWithRetry(() => import('@pages/settings/pages/security'))
export const DecreisDirectivesPage = reactLazyWithRetry(() => import('@pages/decreis-directives'))
export const GetYourLoginPage = reactLazyWithRetry(() => import('@pages/get-your-login'))
export const MemoFreshmenPage = reactLazyWithRetry(() => import('@pages/memo-freshmen'))
export const MemoTeacherPage = reactLazyWithRetry(() => import('@pages/memo-teacher'))
export const MedicalCertificate = reactLazyWithRetry(() => import('@pages/medical-certificate'))
export const Onboarding = reactLazyWithRetry(() => import('@pages/onboarding'))
export const LkNotificationsPage = reactLazyWithRetry(() => import('@pages/lk-notifications'))
